### ISSUE TITLE
Help need to use boilerplate

### ISSUE THREAD

**Issue by lewatt23** [dragonza/react-native-boilerplate#1]
Hello and sorry for jumping in like that  and asking help, just that  i read your medium article and i feel like immutablejs may solve my redux persist problem of my app, sorry i could not ask the question on medium since it contains too much code. 

Okay i have a existing project that  used redux-persist  to persist data but my state is really complex one, as i read from your article  ` redux-persist work well with plain js objects`. So my main problem is how to use your template without overwriting all my existing code base, cause your boilerplate is pretty complex :( and i don't know what to take from the boilerplate or not.
Here is my gitlab that containing some code i use in the project,  am very sorry to ask that but please if you have some time please can you look into what i have done  and guide me through the process? 

[https://gitlab.com/lewatt23/kawlo](https://gitlab.com/lewatt23/kawlo)

Thanks

**Comment by dragonza** [comment]
In my boilerplate, I used redux-persist v4 because `redux-persist` v5 haven't supported ImmutableJS. There is a difference between using v4 and v5. My boilerplate might not be suitable for you as you are using persist v5.

What prob are you having with ImmutableJS in the project? Let me know so I could take a look at your project and see if I can help.

**Comment by lewatt23** [comment]
Thanks for your reply, 
There no problem with redux persist i already switched to version v4, as your boilerplate suggested, my main problem comes from how to use it with redux & redux-sagas. I  wish to how to dispatch and get the sate using ImmutableJS.  Because in your boilerplate is see many utils functions with makes me more confuse about their use. 

Okay in my code i set the state of my application using some methods similar to these below.


 ```
//saga that  add a reply  in firebase
function* addReplyFirebase(action) {
  try {
  
         yield put({ type: t.CREATE_REPLY_SUCCESS, payload: {loadaddreply:true} });

         const result = yield call(api.createReply,action.data);
        

         yield put({ type: t.CREATE_REPLY_SUCCESS, payload: {loadaddreply:true} });

         const reply = yield call(api.getReply,action.data);
         yield put({ type: t.GET_REPLY_SUCCESS, payload: {loadaddreply:false,answers:reply} });
         

         
     } catch (error) {
         console.log('saga fail: ', error);
         yield put({ type: t.CREATE_REPLY_FAILED, payload: {loadaddreply:false} });
     }
 }
```

My question is how can i modify such code ( and the rest  like my reducer ), to follow your boilerplate, without  overwriting everything i did so far. I don't know if am clear enough ^^'
Thanks

**Comment by dragonza** [comment]
so my understanding is you want to apply ImmutableJS to your code. To do so, you need to change you reducers to use ImmutableJS. The state would be an ImmutableJS object. Something like this. You need to look up Immutable docs to know which method to you. 

```
import * as t from './actionTypes';
import { fromJS } from 'immutable';

let initialState = fromJS({ isLoggedIn: false,note:[],loading:false });

const notesReducer = (state = initialState, action) => {
  switch (action.type) {
    case t.GET_NOTES_START:
     return state.mergeDeep(state, action.val) // this will return a new ImmutableJS. 
    default:
      return state;
  }
};

export default notesReducer;
```
and then in your component to get the value of your state, you need to use something like

```
import React from 'react'

function ExampleComponent(props) {
  const { note } = props; 
  return (
     <div>{note.get('title)}</div>
  )
}

export default ExampleComponent;
```

Other thing else can stay the same.

**Comment by lewatt23** [comment]
Thanks very much, it worked!!
